# Generated by Django 2.0 on 2018-07-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['-ordering']},
        ),
        migrations.AlterField(
            model_name='order',
            name='table_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.Table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_using',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='ordering',
            field=models.IntegerField(default=0, help_text='bigger the better'),
        ),
    ]
