# Generated by Django 2.0 on 2018-07-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
    ]
